plugins:
  - react
  - react-hooks
  - import
  - jsx-a11y
  - unicorn
  - sonarjs
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:jsx-a11y/strict
  - plugin:unicorn/all
  - plugin:sonarjs/recommended
root: true
env:
  browser: true
  es2021: true
globals:
  process: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
settings:
  react:
    version: detect
overrides:
  - files: 
    - '*.graphql'
    extends: plugin:@graphql-eslint/operations-all
    parserOptions:
      operations: './app/graphql/*.graphql'
    rules:
      '@graphql-eslint/require-id-when-available': off
      '@graphql-eslint/executable-definitions': off
      '@graphql-eslint/fields-on-correct-type': off
      '@graphql-eslint/fragments-on-composite-type': off
      '@graphql-eslint/known-argument-names': off
      '@graphql-eslint/known-directives': off
      '@graphql-eslint/known-fragment-names': off
      '@graphql-eslint/known-type-names': off
      '@graphql-eslint/lone-anonymous-operation': off
      '@graphql-eslint/no-fragment-cycles': off
      '@graphql-eslint/no-undefined-variables': off
      '@graphql-eslint/no-unused-fragments': off
      '@graphql-eslint/no-unused-variables': off
      '@graphql-eslint/one-field-subscriptions': off
      '@graphql-eslint/overlapping-fields-can-be-merged': off
      '@graphql-eslint/possible-fragment-spread': off
      '@graphql-eslint/provided-required-arguments': off
      '@graphql-eslint/scalar-leafs': off
      '@graphql-eslint/unique-argument-names': off
      '@graphql-eslint/unique-directive-names-per-location': off
      '@graphql-eslint/unique-variable-names': off
      '@graphql-eslint/value-literals-of-correct-type': off
      '@graphql-eslint/variables-are-input-types': off
      '@graphql-eslint/variables-in-allowed-position': off
      '@graphql-eslint/no-deprecated': off
      '@graphql-eslint/alphabetize': off
      '@graphql-eslint/match-document-filename':
        - error
        - fragment:
            style: PascalCase
          query:
            style: PascalCase
            suffix: Query
          mutation:
            style: PascalCase
            suffix: Mutation
      '@graphql-eslint/naming-convention':
        - error
        - types: PascalCase
          FieldDefinition: PascalCase
          allowLeadingUnderscore: true
rules:
  accessor-pairs: error
  array-bracket-newline: error
  array-bracket-spacing: error
  array-callback-return: error
  array-element-newline:
    - error
    - consistent
  arrow-parens: 
    - error
    - as-needed
  arrow-spacing: error
  arrow-body-style: error
  block-spacing: 
    - error
    - never
  block-scoped-var: error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase: error
  class-methods-use-this: error
  comma-style: error
  comma-dangle: error
  comma-spacing: error
  complexity: error
  computed-property-spacing: error
  consistent-this: error
  eqeqeq: warn
  default-case: error
  default-case-last: error
  default-param-last: error
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last:
    - error
    - never
  func-name-matching: error
  func-names: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  func-call-spacing: error
  function-call-argument-newline: 
    - error
    - consistent
  function-paren-newline: 
    - error
    - consistent
  generator-star-spacing: error
  grouped-accessor-pairs: error
  guard-for-in: error
  implicit-arrow-linebreak: error
  quotes: 
    - error
    - single
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  lines-between-class-members: error
  max-classes-per-file: error
  max-depth: error
  max-lines: error
  max-nested-callbacks: error
  max-params: error
  new-cap: error
  new-parens: error
  no-array-constructor: error
  no-await-in-loop: error
  no-bitwise: error
  no-caller: error
  no-alert: warn
  no-console: 
    - warn
    - allow: [ error, warn ]
  no-confusing-arrow: error
  no-constructor-return: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-extra-parens: 
    - error
    - functions
  no-multi-spaces: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-multi-assign: error
  no-multi-str: error
  no-negated-condition: error
  no-multiple-empty-lines: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-promise-executor-return: error
  no-plusplus: 
    - error
    - allowForLoopAfterthoughts: true
  no-proto: error
  no-restricted-exports: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-tabs: error
  no-trailing-spaces: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-undef-init: error
  no-shadow: error
  no-unused-vars: warn
  no-underscore-dangle: 
    - error
    - allow: [ _id ]
  no-unused-expressions: error
  no-undefined: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-private-class-members: error
  no-use-before-define: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-whitespace-before-property: error
  no-warning-comments: warn
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: 
    - error
    - always
  object-shorthand: error
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padding-line-between-statements: error
  padded-blocks: 
    - error
    - never
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-named-capture-group: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  radix: error
  require-atomic-updates: error
  require-await: error
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  semi-style: error
  space-before-blocks: 
    - error
    - never
  space-before-function-paren: 
    - error
    - never
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  sort-imports: 
    - warn
    - ignoreDeclarationSort: true
  sort-vars: error
  spaced-comment: error
  strict: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  vars-on-top: error
  wrap-iife: error
  yield-star-spacing: error
  yoda: error
  react/prop-types: off
  react/no-unescaped-entities:
    - error
    - forbid: [ ">", "}", "\"" ]
  react/forbid-foreign-prop-types: 
    - warn
    - allowInPropTypes: true
  react/function-component-definition: error
  react/no-access-state-in-setstate: error
  react/no-adjacent-inline-elements: error
  react/no-array-index-key: error
  react/no-arrow-function-lifecycle: error
  react/no-danger: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-invalid-html-attribute: error
  react/no-namespace: error
  react/no-redundant-should-component-update: error
  react/no-this-in-sfc: error
  react/no-typos: error
  react/no-unsafe: error
  react/no-unstable-nested-components: error
  react/no-unused-class-component-methods: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-es6-class: error
  react/prefer-stateless-function: error
  react/require-optimization: error
  react/self-closing-comp: error
  react/sort-comp: error
  react/state-in-constructor: error
  react/static-property-placement: error
  react/style-prop-object: error
  react/void-dom-elements-no-children: error
  react/jsx-boolean-value: error
  react/jsx-child-element-spacing: error
  react/jsx-closing-bracket-location: error
  react/jsx-closing-tag-location: error
  react/jsx-curly-brace-presence: error
  react/jsx-curly-newline: error
  react/jsx-curly-spacing: error
  react/jsx-equals-spacing: error
  react/jsx-first-prop-new-line: error
  react/jsx-fragments: error
  react/jsx-handler-names: error
  react/jsx-indent: 
    - error
    - 2
  react/jsx-indent-props: 
    - error
    - 2
  react/jsx-max-props-per-line:
    - error
    - when: multiline
  react/jsx-newline: 
    - error
    - prevent: true
  react/jsx-no-bind: error
  react/jsx-no-script-url: error
  react/jsx-no-useless-fragment: error
  react/jsx-pascal-case: error
  react/jsx-props-no-multi-spaces: error
  react/jsx-wrap-multilines: error
  react/destructuring-assignment: error
  import/first: error
  import/no-amd: error
  import/no-anonymous-default-export: warn
  import/no-webpack-loader-syntax: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  unicorn/prevent-abbreviations: off
  unicorn/no-null: off
  unicorn/filename-case:
    - error
    - case: pascalCase
  unicorn/numeric-separators-style:
    - error
    - onlyIfContainsSeparator: true
  sonarjs/no-duplicate-string: 
    - error
    - 7
  sonarjs/no-nested-template-literals: off
  sonarjs/cognitive-complexity:
    - error
    - 25