[build]
    publish = "public"
    command = "npm run build"

[[redirects]]
    from = "https://kittenlocks.netlify.app/*"
    to = "https://www.kittenlocks.de/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/*-worker.js"
    [headers.values]
        cache-control = 'no-cache'

[[headers]]
    for = "/workbox-*.js"
    [headers.values]
        cache-control = 'no-cache'